create type "public"."game_state" as enum ('created', 'registering', 'active', 'completed');

create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "registration_start_date" timestamp with time zone not null,
    "game_start_date" timestamp with time zone not null,
    "current_round_id" bigint,
    "completed" boolean not null default false,
    "max_rounds" bigint not null,
    "sponsor_id" bigint,
    "round_length_minutes" bigint not null,
    "winner_id" bigint,
    "winner_reward" double precision,
    "state" game_state not null default 'created'::game_state
);


alter table "public"."games" enable row level security;

create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "round_id" bigint not null,
    "player1_id" bigint not null,
    "player2_id" bigint,
    "player1_move" smallint,
    "player2_move" smallint,
    "winner_id" bigint
);


alter table "public"."matches" enable row level security;

create table "public"."rounds" (
    "id" bigint generated by default as identity not null,
    "game_id" bigint not null,
    "round_number" bigint not null,
    "end_time" timestamp with time zone not null
);


alter table "public"."rounds" enable row level security;

create table "public"."user_registration" (
    "id" bigint generated by default as identity not null,
    "game_id" bigint not null,
    "user_id" bigint not null,
    "registered_at" timestamp with time zone not null default now(),
    "token_balance" double precision,
    "force" boolean not null
);


alter table "public"."user_registration" enable row level security;

create table "public"."users" (
    "id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "display_name" text not null,
    "image" text
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX rounds_pkey ON public.rounds USING btree (id);

CREATE UNIQUE INDEX user_registration_pkey ON public.user_registration USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."rounds" add constraint "rounds_pkey" PRIMARY KEY using index "rounds_pkey";

alter table "public"."user_registration" add constraint "user_registration_pkey" PRIMARY KEY using index "user_registration_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."games" add constraint "games_current_round_id_fkey" FOREIGN KEY (current_round_id) REFERENCES rounds(id) ON DELETE SET NULL not valid;

alter table "public"."games" validate constraint "games_current_round_id_fkey";

alter table "public"."games" add constraint "games_winner_id_fkey" FOREIGN KEY (winner_id) REFERENCES users(id) not valid;

alter table "public"."games" validate constraint "games_winner_id_fkey";

alter table "public"."matches" add constraint "matches_player1_id_fkey" FOREIGN KEY (player1_id) REFERENCES users(id) not valid;

alter table "public"."matches" validate constraint "matches_player1_id_fkey";

alter table "public"."matches" add constraint "matches_player2_id_fkey" FOREIGN KEY (player2_id) REFERENCES users(id) not valid;

alter table "public"."matches" validate constraint "matches_player2_id_fkey";

alter table "public"."matches" add constraint "matches_round_id_fkey" FOREIGN KEY (round_id) REFERENCES rounds(id) not valid;

alter table "public"."matches" validate constraint "matches_round_id_fkey";

alter table "public"."matches" add constraint "matches_winner_id_fkey" FOREIGN KEY (winner_id) REFERENCES users(id) not valid;

alter table "public"."matches" validate constraint "matches_winner_id_fkey";

alter table "public"."rounds" add constraint "rounds_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) not valid;

alter table "public"."rounds" validate constraint "rounds_game_id_fkey";

alter table "public"."user_registration" add constraint "user_registration_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) not valid;

alter table "public"."user_registration" validate constraint "user_registration_game_id_fkey";

alter table "public"."user_registration" add constraint "user_registration_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."user_registration" validate constraint "user_registration_user_id_fkey";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."rounds" to "anon";

grant insert on table "public"."rounds" to "anon";

grant references on table "public"."rounds" to "anon";

grant select on table "public"."rounds" to "anon";

grant trigger on table "public"."rounds" to "anon";

grant truncate on table "public"."rounds" to "anon";

grant update on table "public"."rounds" to "anon";

grant delete on table "public"."rounds" to "authenticated";

grant insert on table "public"."rounds" to "authenticated";

grant references on table "public"."rounds" to "authenticated";

grant select on table "public"."rounds" to "authenticated";

grant trigger on table "public"."rounds" to "authenticated";

grant truncate on table "public"."rounds" to "authenticated";

grant update on table "public"."rounds" to "authenticated";

grant delete on table "public"."rounds" to "service_role";

grant insert on table "public"."rounds" to "service_role";

grant references on table "public"."rounds" to "service_role";

grant select on table "public"."rounds" to "service_role";

grant trigger on table "public"."rounds" to "service_role";

grant truncate on table "public"."rounds" to "service_role";

grant update on table "public"."rounds" to "service_role";

grant delete on table "public"."user_registration" to "anon";

grant insert on table "public"."user_registration" to "anon";

grant references on table "public"."user_registration" to "anon";

grant select on table "public"."user_registration" to "anon";

grant trigger on table "public"."user_registration" to "anon";

grant truncate on table "public"."user_registration" to "anon";

grant update on table "public"."user_registration" to "anon";

grant delete on table "public"."user_registration" to "authenticated";

grant insert on table "public"."user_registration" to "authenticated";

grant references on table "public"."user_registration" to "authenticated";

grant select on table "public"."user_registration" to "authenticated";

grant trigger on table "public"."user_registration" to "authenticated";

grant truncate on table "public"."user_registration" to "authenticated";

grant update on table "public"."user_registration" to "authenticated";

grant delete on table "public"."user_registration" to "service_role";

grant insert on table "public"."user_registration" to "service_role";

grant references on table "public"."user_registration" to "service_role";

grant select on table "public"."user_registration" to "service_role";

grant trigger on table "public"."user_registration" to "service_role";

grant truncate on table "public"."user_registration" to "service_role";

grant update on table "public"."user_registration" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


